launch/.env.example, launch/docker-compose.yml, launch/genesis.json, launch/init.sh, launch/nginx.conf
デプロイに関するファイルの定義のPRです
* launch/init.sh
+ チェーン初期化用のシェルスクリプト、以前書いたものとほぼ同じ仕様のものです
* launch/docker-compose.yml 
+ デーモン、REST APIとpricefeedとREST APIのcors対策のnginxを起動します
=> デプロイ用スクリプトなどの定義

launch/generate.sh, launch/init.sh
=> generate.shの追加

x/auction/keeper/keeper_test.go
`auction := types.NewSurplusAuction("some_module", c("usdx", 100), "jpyx", someTime).WithID(id)`
bidDenomはjpyxに変更していますが，lot types.Coinはusdxのままで大丈夫でしょうか？
その他はabciをtmprotoにするなど，軽微な変更です。
=> feat: keeper test

x/jsmndist/types/params_test.go
- jsmndisttypes "github.com/lcnem/jpyx/x/jsmndist/types"
上記のディレクトリ修正のみです。
@KimuraYu45z @YasunoriMATSUOKA 
特に変更なしですが、レビューお願いします。
=> Jsmndist param

.vscode/extensions.json, .vscode/settings.json
作業メンバーの環境を合わせるために
https://github.com/CauchyE/rules
よりGolang用のsettings.jsonとextensions.jsonを移植
@YasunoriMATSUOKA @KimuraYu45z 
確認ともし追加するものがあればお願いします
=> chore: vscode extension setting

app/test_common.go
=> fix: fix legacy codec.MarshalJSONIndent

x/auction/types/auctions_test.go
@KimuraYu45z 
@Senna46 
@YasunoriMATSUOKA 
レビューお願い致します
=> test: fix prefix and type

x/cdp/keeper/deposit_test.go
@KimuraYu45z @Senna46 @Tomosuke0930 
テストPassする状態になりました。レビューお願いします。トークンの名前はおそらく本質ではないと思うので、後で( @Tomosuke0930 に)対応(をお願い)しようと思っていますが、各ファイル都度都度今やっておいたほうがよさそうであれば、その旨、ご指摘ください。
=> test: fix type mismatch

x/cdp/types/cdp_test.go
@KimuraYu45z @Senna46 @Tomosuke0930 
レビューお願いします。
=> test: x/cdp/types/cdp_test.go fix error message

app/app.go, cmd/jpyxd/cmd/root.go
=> App refactor

x/cdp/client/cli/query_cdp.go, x/cdp/keeper/cdps.go, x/cdp/keeper/cdps_test.go, x/cdp/keeper/grpc_query_cdp.go
@KimuraYu45z cc: @Senna46 @taro04 
レビューお願いします。
createしたはずのcdpがGetできていない問題のデバッグ用にfmt.Printfを追加して、デプロイして、デバッグしてみるためのものです。
デバッグ中に、追記したテストも一部入っています。
=> chore: debug get cdp list

x/cdp/handler_cdp.go, x/cdp/keeper/cdps.go, x/cdp/keeper/deposit.go, x/cdp/keeper/grpc_query_cdp.go, x/cdp/keeper/keeper.go, x/cdp/types/cdp.go, x/incentive/keeper/keeper.go, x/incentive/keeper/rewards.go
@KimuraYu45z cc: @Senna46 @taro04 
レビューお願いします。
cdp createで異常箇所をひとつずつ処理を追って特定するために、fmt.Printfを追加してみました。
デバッグ進めるにあたり、足りてない箇所等あれば、ご指摘頂けると助かります。
お手数ですがよろしくお願いします。
=> chore: add debug comment to cdp create

x/cdp/client/cli/query_cdp.go, x/cdp/handler_cdp.go, x/cdp/keeper/cdps.go, x/cdp/keeper/params.go
@KimuraYu45z 
レビューお願いします。
printの書き方で、値が変わってしまっている問題がありそうなので、修正という内容です。
=> fix: bad print

faucet/docker-compose.yml
@KimuraYu45z 
レビューお願いします。
faucet関連コンテナで、nginxリバースプロキシだけ、明示的に名前をつけていなかったので、他と揃えて名前を付けました。
=> chore: add container name

README.md
@KimuraYu45z 
レビューお願いします。
ノードの起動手順、その過程で関連する設定ファイル、一部用語等に関する情報を追記しました。
=> fix: readme to clarify node startup procedures

cmd/ununifid/cmd/root.go
Implemented a function to automatically enable api
=> feat: implement init config func

faucet/nginx.conf
=> hotfix: update nginx.conf to support ipv6

faucet/docker-compose.yml, faucet/nginx.conf
Added two faucet assets, ueth and euu.
=> feat: add faucet asset

Dockerfile
ununifdに必要なライブラリが最終イメージになかった
最終イメージに依存ライブラリを追加
=> modify: fix docker ununfi depend

README.md
=> fix: readme version of mainnet

docs/client/config.json, docs/client/swagger.yaml
Generated swagger.yaml for updating ununifi-ts under newDevelop branch.
=> gen-swagger.sh to generate swagger.yaml

networks/README.md, networks/ununifi-beta/upgrades/v1-beta.2/guide.md
Specific docs for the upgrade named `v1-beta.2`.
=> WIP: create networks dir

networks/ununifi-beta/upgrades/v1-beta.2/guide.md
This PR is to fix the information related to the upgrade block height and time.
=> Fix/upgrade v1 beta.2 doc

x/nftmarket/keeper/grpc_query.go
=> fix: fix wrong argument of BidderBids

app/upgrades/README.md, networks/ununifi-beta/upgrades/v1-beta.3/guide.md
- Some modification from the previous `v1-beta.2` document
- Changed block height and estimated time 
- Checksum info
=> Doc/upgrade v1 beta.3

x/nftmarket/keeper/querier.go
=> modify wrong imported types package

x/nftmint/client/cli/query.go
=> modify query description in cli

x/nftmint/client/cli/tx.go
=> remove wrong flag set for mint-nft

x/nftmarket/keeper/loan.go, x/nftmarket/types/errors.go
issue #291 
the new error log is:
```
"raw_log": "failed to execute message; message index: 0: not borrowed yet once",
```
=> add error case into repay method and add new error type to return

x/nftmarket/keeper/loan.go, x/nftmarket/keeper/loan_test.go, x/nftmarket/keeper/nft_listing.go, x/nftmarket/keeper/nft_listing_test.go
=> add logic to manage loan data

x/nftmint/keeper/class.go, x/nftmint/keeper/nft.go
driven by #320 .
Modification point is
`len(bz) == 0` -> `bz == nil` 
in x/nftmint module
=> modify the way of the []byte condition

x/derivatives/abci.go, x/derivatives/types/genesis_test.go, x/derivatives/types/params.go
added default param values and modify var type handling in abci.go in reflection to the modification of the proto in the previous PR( This was the cause of build error).
=> add default param set

x/derivatives/keeper/lpt.go
Reflection of these comments: https://github.com/UnUniFi/chain/pull/363
=> fix slight stuff

x/derivatives/keeper/keeper_test.go
issue: #360 
@inotite 
Plz check if these initial setting is suited for the tests in x/derivaitves you wrote.
if not, plz modify and let me know.
=> modify initial setting for test suite

scripts/commands/derivatives/.env.pricefeed, scripts/commands/derivatives/start.sh
- modified start.sh and env for pricefeed to support uusdc posting
=> support uusdc pricefeed in script

x/derivatives/keeper/grpc_query.go, x/derivatives/keeper/keeper_test.go, x/derivatives/keeper/lpt.go, x/derivatives/keeper/lpt_test.go
Addressed issues: #364 and #370 
beside, impled very simple test for newly added fn with the modification of the test suite setup.
tested in cli as well.
=> impl fn to detemine initial lpt supply amount

scripts/setup/init.sh
I fixed init.sh for set pool_params.
=> fix: derivatives init.sh fix

docs/core/proto-docs.md, proto/derivatives/tx.proto, x/derivatives/client/cli/tx.go, x/derivatives/keeper/lpt.go, x/derivatives/keeper/lpt_test.go, x/derivatives/keeper/msg_server.go, x/derivatives/types/codec.go, x/derivatives/types/msgs.go, x/derivatives/types/tx.pb.go
close https://github.com/UnUniFi/chain/issues/434
=> chore: derivatives rename

x/yield-aggregator/README.md
=> feat: IYA audit README

networks/ununifi-beta/upgrades/v2.1.0/guide.md
Update v2.0.1 guide for v2.0.1
@KimuraYu45z Plz check.
=> feat: v2.1.0 guide

x/derivatives/keeper/perpetual_futures.go
close #538
Change commission fee based on margin => position size
Next
Change commission rate on params
=> fix: commission fee based on position-size

x/pricefeed/genesis_test.go, x/pricefeed/integration_test.go
=> fix: ci test

go.mod, go.sum, x/pricefeed/keeper/integration_test.go, x/pricefeed/keeper/keeper_test.go, x/pricefeed/keeper/params_test.go, x/pricefeed/types/genesis_test.go, x/pricefeed/types/market_test.go, x/pricefeed/types/msgs_test.go
Update wasmd 0.40.1 & wasmvm v1.2.4
=> Wasmd 0.40.1

x/derivatives/keeper/perpetual_futures.go
close #500
If the margin is negative, the commission is lowered and adjusted margin to 0
=> fix: negative margin (ReportLiquidation & LevyPeriod)

x/derivatives/keeper/lpt.go
close #488 
- Confirmed we can delete todos in #488 
- Refactored execution orders that modify states in `BurnLiquidityProviderToken` for better operation
- Added comments for the explicit
=> Delete unnecessary todo, refactor execution order and add comments in BurnLiquidyProviderToken fn

x/derivatives/keeper/margin.go, x/derivatives/keeper/perpetual_futures.go, x/derivatives/keeper/perpetual_futures_test.go, x/derivatives/keeper/pool.go, x/derivatives/keeper/pool_test.go, x/derivatives/keeper/positions.go
- Fix for #520 bug
- Corrected a mistake in the processing of Reserve
=> fix: Derivatives Test ＆ Bug

x/derivatives/keeper/margin.go, x/derivatives/keeper/margin_test.go, x/derivatives/keeper/perpetual_futures_test.go
close #626 
- Implement unit tests of AddMargin and WithdrawMargin
- Fix function call in other test
- Modify the way to subtract in WithdrawMargin
=> Impl unit tests of margin msgs (AddMargin and WithdrawMargin)

app/keepers/keepers.go, testutil/keeper/derivatives.go, x/derivatives/keeper/keeper.go, x/derivatives/keeper/keeper_test.go, x/derivatives/keeper/nft.go, x/derivatives/keeper/test/08_position_send_nft.sh, x/derivatives/keeper/test/09_position_pending_payment.sh, x/derivatives/types/expected_keepers.go
Eliminate dependence on `nftfactory` module and mint position NFTs with `nft` module
=> Eliminate the use of Nftfactory in Derivatives

app/keepers/keepers.go
Add hooksICS4 Wrapper to ibcRouter's transferStack
Ref https://github.com/cosmos/ibc-apps/blob/main/modules/ibc-hooks/README.md
=> fix: hooks middleware

wasmbinding/bindings/msg.go, wasmbinding/message_plugin.go, x/irs/keeper/msg_server_deposit_to_tranche.go, x/irs/keeper/msg_server_withdraw_from_tranche.go, x/irs/keeper/tranche.go, x/irs/types/errors.go
- Separate logic & fix handling
- Add deputyDepositToTranche
=> DeputyDepositToTranche via IBC-hooks

x/irs/keeper/grpc_query_estimate_mint_pt_yt_pair.go, x/irs/keeper/stripping.go, x/irs/keeper/swap.go
Add denom error handling into Querys & Msgs.
=> feat: add error handling

x/irs/keeper/grpc_query_estimate_swap_matured_yt_to_ut.go, x/irs/keeper/grpc_query_tranche_apys.go, x/irs/keeper/swap_advanced.go, x/irs/types/constants.go, x/irs/types/pool.go
Fix Pow() issue
- Pow() integer exponent too large >512
Use ` log(y^n) = n * log(y)` to solve this problem
Fix some Edge cases, refactor queries
=> Some fix for IRS
