launch/docker-compose.yml

CORS対策用に追加していたnginxコンテナの起動をdocker-composeから削除

nginxコンテナの削除

---

x/auction/types/msg_test.go
x/auction/types/params_test.go

auction/typesにmsg_test.goとparams_test.goをKavaよりコピー
ブロックチェーン自体のテストを含まないので変更なしです。
@KimuraYu45z @YasunoriMATSUOKA 
レビューお願いします
残り、Genesis Auction関連のテスト２件でAuctionは終わりですが、仕様変更への対応で一部相談したいのですが可能でしょうか？

msg params test

---

x/auction/types/genesis_test.go

typesの方のgenesis_test.goも作成しました。
- Auction型を要求されている3変数をUnpack
- Any型を要求されている1変数をPack
@KimuraYu45z @YasunoriMATSUOKA 
レビューお願いします。
VSCode上でインポートの`auctiontypes "github.com/lcnem/jpyx/x/auction/types"`がエラーとなっているのですが、原因わかりますでしょうか？
私の環境だけの問題だったらいいのですが、今回、PackとUnpackを使用するにあたり、インポートに追加しています。

feat: auction types genesis

---

app/test_common.go
x/auction/abci_test.go
x/auction/keeper/auctions_test.go
x/cdp/abci_test.go
x/cdp/keeper/auctions_test.go
x/cdp/keeper/deposit_test.go
x/cdp/keeper/draw_test.go
x/cdp/keeper/keeper_bench_test.go
x/cdp/keeper/seize_test.go
x/incentive/keeper/integration_test.go
x/incentive/keeper/payout_test.go
x/jsmndist/keeper/mint_test.go

`authtypes.ModuleCdc.MustMarshalJSON`を`tApp.appCodec.MustMarshalJSON`に変更
レガシーのAminoからprotoへ
引数にtAppを追加

fix: legacy amino to proto

---

x/cdp/keeper/draw_test.go

@KimuraYu45z cc: @Senna46 @Tomosuke0930 
以下のテストがPassできず、修正方針迷っています。
https://github.com/lcnem/jpyx/blob/ae2faae26866b90cf6191dcfa2713bb3855e0d21/x/cdp/keeper/draw_test.go#L184
テスト実行結果
```
Running tool: /usr/local/go/bin/go test -timeout 30s -run ^TestDrawTestSuite$ -testify.m ^(TestModuleAccountFailure)$ github.com/lcnem/jpyx/x/cdp/keeper
--- FAIL: TestDrawTestSuite (0.01s)
--- FAIL: TestDrawTestSuite/TestModuleAccountFailure (0.01s)
/home/yasunori_matsuoka/github.com/lcnem/jpyx/x/cdp/keeper/draw_test.go:185: 
Error Trace:	draw_test.go:185
Error:      	func (assert.PanicTestFunc)(0x1458b20) should panic
Panic value:	<nil>
Test:       	TestDrawTestSuite/TestModuleAccountFailure
FAIL
exit status 1
FAIL	github.com/lcnem/jpyx/x/cdp/keeper	0.045s
``` …

test: fix x/cdp/keeper/draw 

---

x/incentive/keeper/payout_test.go

Goはaliasつけたタイプを別型として認識するクソ仕様
それの対策が必要

fix: []period to periods

---

x/auction/genesis_test.go

テスト自体はまだ落ちるが、
*codectypes.Anyとauctiontypes.Auctionの比較をしていて落ちたのは治した
auctiontypes.Auctionとauctiontypes.Auctionの比較でフィールドが違うので引き続き落ちています

fix: unpack-auction

---

x/incentive/types/genesis_test.go

GenesisAccumulationTimes型がhard関連と思われるRewardFactorを持たないように仕様変更されていたので、テスト自体を削除
参考
```
type GenesisAccumulationTime struct {
CollateralType           string    `protobuf:"bytes,1,opt,name=collateral_type,json=collateralType,proto3" json:"collateral_type,omitempty" yaml:"collateral_type"`
PreviousAccumulationTime time.Time `protobuf:"bytes,2,opt,name=previous_accumulation_time,json=previousAccumulationTime,proto3,stdtime" json:"previous_accumulation_time" yaml:"previous_accumulation_time"`
}
```
close #71
@KimuraYu45z @YasunoriMATSUOKA @Tomosuke0930 
削除で問題ないか確認お願いします。

fix: delete invalid reward factor test

---

faucet/deploy.sh
faucet/docker-compose.yml
faucet/nginx.conf

@KimuraYu45z cc: @taro04 @Senna46 
レビューお願いします。関連プルリクもセットの内容になります。
FaucetのバックエンドAPIをdenom毎に分割して、denom毎に引き出し制限数量等変えて動作させるための修正と、botanyからjpyxレポジトリに移すという修正です。
バックエンドの修正内容はこれで完了となりますのでこちらのプルリクはレビューお願いします。
フロントエンド側の修正は以下プルリクで作業中で未完ですが、明日完了くらいの見込みです。フロントエンド側の修正もマージでき次第、改めて諸々デプロイします。動作確認取れたら最後にbotany側に残ったFaucetの実装を消します。
関連プルリク
https://github.com/lcnem/telescope/pull/166
https://github.com/lcnem/botany/pull/122

feat: faucet backend api and reverse proxy

---

x/auction/keeper/grpc_query_auction.go
x/auction/keeper/keeper.go

@KimuraYu45z @YasunoriMATSUOKA 
x/cdp/keeper/cdps.go　なども参考に確認したところ、x/auction/keeper/grpc_query_auction.go　のGetAuctionが最後まで通ったときに返すのが、trueなのが原因で、"not found"エラーになっている気がするのこのPRで一度確認させてください。

fix: GetAuction return err

---

faucet/deploy.sh
launch/ununifi-6-test/start-ununifi-6-test.sh

@KimuraYu45z 
レビューお願いします。
ノード上に古いdockerイメージ等が残ってストレージ容量を圧迫しないよう、デプロイスクリプトに古いイメージ等をクリアする実装を加えました。

fix: clear unnecessary docker resources

---

.github/workflows/docker-private-test.yml
launch/ununifi-7-private-test/start-ununifi-7-private-test.sh

@KimuraYu45z 
レビューお願いします。
developブランチにマージされたら、プライベートテストネット用のDockerイメージをタグ: testで公開するGitHub Actionsを作成しました。
次のプライベートテストネットのchain-id=ununifi-7-private-testのローンチ用のスクリプトにもタグの変更を反映しておきました。

feat: cd to publish docker image of private testnet with test tag

---

.github/workflows/docker.yml

@mkXultra 
plz review 🙏 
Disable the CD because if the current CD runs at release time, a Docker image inconsistent with the current public testnet will be published.
And, instead, I will change the CD to be triggered manually.

fix: cd to disable docker image push on release published

---

networks/ununifi-beta/upgrades/v1-beta.3/guide.md

changed the way to test the build status from md5 hash to ununifid version to see the latest commit hash of git

fix md5sum

---

x/derivatives/keeper/lpt.go

issue: #361 
Beside, i think the first lpt minter should get at least more than `1uglp`.
https://github.com/UnUniFi/chain/blob/2853ea3b802ce9b43e0d8a05dade0b2f76a8bb93/x/derivatives/keeper/lpt.go#L50 
So, not merge this yet. waiting for the response.

[WIP] fix sub method error by setting initial mintfee coin

---

x/derivatives/keeper/perpetual_futures.go
x/derivatives/types/positions.go
x/derivatives/types/positions_test.go

fix closing fee

---

x/derivatives/keeper/perpetual_futures.go

Part of #499
Set `LastLeviedAt` time when opening a position.
Fix function `ReportLevyPeriodPerpetualFuturesPosition` corrected errors in position size evaluation.

fix: lavy period when opened position

---

app/app.go
app/test_common.go
go.mod
go.sum
scripts/setup/init.sh
scripts/setup/variables.sh

Disable all ununifi mods (with the exception of wasm)

feat: disable mod

---

x/derivatives/client/cli/tx.go

close #442 
- Remove the string as arg in the code
- Tested by running chain and throwing tx by enabling derivatives module in local

change the way to create any obj

---

x/nftbackedloan/keeper/utils.go
x/nftbackedloan/types/errors.go

close #341
NFT List with MIN_DEPOSIT_RATE greater than 50% is not allowed.

feat: add error that min_deposit_rate too high

---

x/ecosystemincentive/README.md
x/nftbackedloan/keeper/liquidation.go
x/nftbackedloan/keeper/nft_listing.go
x/nftbackedloan/keeper/nft_listing_test.go
x/nftbackedloan/keeper/utils.go

- Injected lacking hooks and modified the location of the hook function
- AfterNftListed
- AfterNftUnlistedWithoutPayment
- Modify unit tests to check hooks status
- Modify README

Inject lacking hooks in nftbackedloan 

---

app/keepers/keepers.go

Some fix for wasm-hooks
https://github.com/cosmos/ibc-apps/tree/main/modules/ibc-hooks

fix: wasm permission

---

x/irs/keeper/amm.go
x/irs/keeper/amm_test.go
x/irs/keeper/stripping.go
x/irs/keeper/swap.go
x/irs/keeper/swap_advanced.go
x/irs/keeper/swap_advanced_test.go
x/irs/keeper/swap_test.go
x/irs/keeper/tranche.go
x/irs/types/errors.go
x/irs/types/pool.go
x/irs/types/pool_test.go

Change AMM code & Impl test
- Added error when StartTime is less than block time
- Added error handling for AMM functions
`k = x1^(1-t) + y1^(1-t)`
If x2 is too large `x2^(1-t) > k`, so `y2^(1-t)` become < 0.
Then `y2 = y2^(1-t)^(1/(1-t))` cannot be calculated.
Therefore, return value should be 0 or y1(all amount in pool).
Current returns 0 (= error), but you may verify that you can give y1 and set y in the pool to 0.
I think error return is a safe now.

feat: AMM, Swap fix and test & impl SwapUtToYt
